version: "3.9"
services:
  backend:
    build:
      context: ../
      dockerfile: infra/dockerfiles/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    working_dir: /app/apps/backend
    volumes:
      - ../:/app

  frontend:
    build:
      context: ../apps/frontend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ../apps/frontend:/app

  voice:
    build:
      context: ../
      dockerfile: infra/dockerfiles/voice.Dockerfile
    environment:
      - AGENT_ROOM_PREFIX=bevpro-
    command: python -m voice.app
    working_dir: /app/apps/voice
    ports:
      - "7000:7000"
    volumes:
      - ../:/app

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

